# Generated by Django 3.2.4 on 2021-08-08 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='liked_users',
            new_name='liked_lectures',
        ),
    ]
