# Generated by Django 3.2.4 on 2021-08-08 06:59

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_rename_liked_users_lecture_liked_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='video_url',
            field=embed_video.fields.EmbedVideoField(null=True),
        ),
    ]
